apiVersion: batch/v1
kind: Job
metadata:
  name: test-ansible-job
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: openshift-ansible
          image: openshift/origin-ansible:v3.11.0
          command: ["ansible-playbook"]
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
                    secretKeyRef:
                            name: default-aws-secret
                            key: awsAccessKeyId                  
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
                    secretKeyRef:
                            name: default-aws-secret
                            key: awsSecretAccessKey

      restartPolicy: Never 
